global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'orchid-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['orchid-service:8080']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']